//
// AccountError.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct AccountError: Codable { 


    public var message: String

    public init(message: String) {
        self.message = message
    }

}
