//
// Accounts.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct Accounts: Codable { 


    public var balance: Double?
    public var code: String?
    public var message: String?
    public var error: String?

    public init(balance: Double?, code: String?, message: String?, error: String?) {
        self.balance = balance
        self.code = code
        self.message = message
        self.error = error
    }

}
