//
// Account.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct Account: Codable { 


    public var balance: Double
    public var code: String
    public var message: String

    public init(balance: Double, code: String, message: String) {
        self.balance = balance
        self.code = code
        self.message = message
    }

}
