//
// AllocationChange.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct AllocationChange: Codable {

    public var asset: Asset
    public var change: Double

    public init(asset: Asset, change: Double) {
        self.asset = asset
        self.change = change
    }

}
