//
// Allocation.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct Allocation: Codable { 


    public var description: String
    public var date: Int
    public var mapping: [String:AssetToPercentMapping]

    public init(description: String, date: Int, mapping: [String:AssetToPercentMapping]) {
        self.description = description
        self.date = date
        self.mapping = mapping
    }

}
