//
// AssetClassAndApy.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct AssetClassAndApy: Codable {

    public var _class: AssetClass
    public var apy: Double

    public init(_class: AssetClass, apy: Double) {
        self._class = _class
        self.apy = apy
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case _class = "class"
        case apy
    }

}
