//
// Asset.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct Asset: Codable {

    public var name: String
    public var _class: AssetClass
    /** Annualised Percentage Performance */
    public var annualizedPerformance: Double?

    public init(name: String, _class: AssetClass, annualizedPerformance: Double? = nil) {
        self.name = name
        self._class = _class
        self.annualizedPerformance = annualizedPerformance
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case _class = "class"
        case annualizedPerformance = "annualized_performance"
    }

}
