//
// AssetClass.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct AssetClass: Codable {

    public enum Typ: String, Codable, CaseIterable {
        case cash = "Cash"
        case equity = "Equity"
        case etf = "Etf"
        case fixed = "Fixed"
        case mutualFund = "MutualFund"
        case other = "Other"
        case custom = "Custom"
    }
    /** what type of asset it is */
    public var typ: Typ
    /** extra info, such as symbol name, used in Custom */
    public var content: String

    public init(typ: Typ, content: String) {
        self.typ = typ
        self.content = content
    }

}
