//
// AssetClassChange.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct AssetClassChange: Codable {

    public var _class: AssetClass
    public var change: Double

    public init(_class: AssetClass, change: Double) {
        self._class = _class
        self.change = change
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case _class = "class"
        case change
    }

}
