//
// AssetToPercentMapping.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct AssetToPercentMapping: Codable { 


    public var percentage: Double

    public init(percentage: Double) {
        self.percentage = percentage
    }

}
