//
// Asset.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct Asset: Codable { 


    public var name: String
    public var _class: String
    /** Annualised Percentage Performance */
    public var performance: Double

    public init(name: String, _class: String, performance: Double) {
        self.name = name
        self._class = _class
        self.performance = performance
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case name
        case _class = "class"
        case performance
    }

}
