//
// BoardType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public enum BoardType: String, Codable, CaseIterable {
    case savings = "savings"
    case spending = "spending"
    case income = "income"
}
