//
// BoardType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public enum BoardType: String, Codable, CaseIterable {
    case savings = "Savings"
    case spending = "Spending"
    case income = "Income"
}
