//
// Event.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct Event: Codable {

    public var name: String
    public var start: Int64
    public var transforms: [Transform]

    public init(name: String, start: Int64, transforms: [Transform]) {
        self.name = name
        self.start = start
        self.transforms = transforms
    }

}
