//
// GoalMetric.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public enum GoalMetric: String, Codable, CaseIterable {
    case savings = "Savings"
    case spending = "Spending"
    case income = "Income"
}
