//
// GoalNewPayload.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct GoalNewPayload: Codable { 


    public enum GoalSide: String, Codable {
        case above = "above"
        case below = "below"
    }
    public var name: String
    public var period: TimePeriod
    public var threshold: Double
    public var goalSide: GoalSide

    public init(name: String, period: TimePeriod, threshold: Double, goalSide: GoalSide) {
        self.name = name
        self.period = period
        self.threshold = threshold
        self.goalSide = goalSide
    }

    public enum CodingKeys: String, CodingKey { 
        case name
        case period
        case threshold
        case goalSide = "goal_side"
    }

}
