//
// Goal.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct Goal: Codable { 


    public enum GoalSide: String, Codable {
        case above = "above"
        case below = "below"
    }
    public var id: String
    public var name: String
    public var period: TimePeriod
    public var threshold: Double
    public var goalSide: GoalSide
    public var completed: Bool
    public var feasible: Bool?

    public init(id: String, name: String, period: TimePeriod, threshold: Double, goalSide: GoalSide, completed: Bool, feasible: Bool?) {
        self.id = id
        self.name = name
        self.period = period
        self.threshold = threshold
        self.goalSide = goalSide
        self.completed = completed
        self.feasible = feasible
    }

    public enum CodingKeys: String, CodingKey { 
        case id = "_id"
        case name
        case period
        case threshold
        case goalSide = "goal_side"
        case completed
        case feasible
    }

}
