//
// GoalNewPayload.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct GoalNewPayload: Codable { 


    public var name: String
    public var start: Int64
    public var end: Int64
    public var threshold: Double
    public var metric: GoalMetric

    public init(name: String, start: Int64, end: Int64, threshold: Double, metric: GoalMetric) {
        self.name = name
        self.start = start
        self.end = end
        self.threshold = threshold
        self.metric = metric
    }

}
