//
// GoalAndStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct GoalAndStatus: Codable { 


    public var goal: Goal
    public var progress: Double

    public init(goal: Goal, progress: Double) {
        self.goal = goal
        self.progress = progress
    }

}
