//
// Insight.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct Insight: Codable { 


    public var title: String
    public var description: String
    public var logo: String?
    public var typ: String
    public var dismissed: Bool

    public init(title: String, description: String, logo: String?, typ: String, dismissed: Bool) {
        self.title = title
        self.description = description
        self.logo = logo
        self.typ = typ
        self.dismissed = dismissed
    }

}
