//
// Insight.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct Insight: Codable { 


    public enum InsightType: String, Codable, CaseIterable {
        case productRecommendation = "ProductRecommendation"
        case savings = "Savings"
        case spending = "Spending"
        case income = "Income"
        case goal = "Goal"
        case incomplete = "Incomplete"
    }
    public var id: MongoObjectID
    public var title: String
    public var description: String
    public var insightType: InsightType
    public var dismissed: Bool
    public var generationTime: Int64
    public var imageURL: String?

    public init(id: MongoObjectID, title: String, description: String, insightType: InsightType, dismissed: Bool, generationTime: Int64, imageURL: String?) {
        self.id = id
        self.title = title
        self.description = description
        self.insightType = insightType
        self.dismissed = dismissed
        self.generationTime = generationTime
        self.imageURL = imageURL
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case id = "_id"
        case title
        case description
        case insightType = "insight_type"
        case dismissed
        case generationTime = "generation_time"
        case imageURL
    }

}
