//
// ItemIdResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ItemIdResponse: Codable {

    /** Item ID for newly added account */
    public var itemId: String

    public init(itemId: String) {
        self.itemId = itemId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case itemId = "item_id"
    }

}
