//
// KnownFinancialProduct.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct KnownFinancialProduct: Codable {

    public var name: String
    public var typ: String
    public var logo: String
    public var productUrl: String

    public init(name: String, typ: String, logo: String, productUrl: String) {
        self.name = name
        self.typ = typ
        self.logo = logo
        self.productUrl = productUrl
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case typ
        case logo
        case productUrl = "product_url"
    }

}
