//
// LinkTokenCreateResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct LinkTokenCreateResponse: Codable { 


    public var linkToken: String
    public var expiration: String
    public var requestId: String?

    public init(linkToken: String, expiration: String, requestId: String?) {
        self.linkToken = linkToken
        self.expiration = expiration
        self.requestId = requestId
    }

    public enum CodingKeys: String, CodingKey { 
        case linkToken = "link_token"
        case expiration
        case requestId = "request_id"
    }

}
