//
// Location.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct Location: Codable { 


    public var hasLocation: Bool
    public var lat: Double
    public var lon: Double

    public init(hasLocation: Bool, lat: Double, lon: Double) {
        self.hasLocation = hasLocation
        self.lat = lat
        self.lon = lon
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case hasLocation = "has_location"
        case lat
        case lon
    }

}
