//
// Money.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct Money: Codable { 


    public var amount: Double

    public init(amount: Double) {
        self.amount = amount
    }

}
