//
// PlaidJWT.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct PlaidJWT: Codable { 


    public var alg: String
    public var kid: String
    public var typ: String

    public init(alg: String, kid: String, typ: String) {
        self.alg = alg
        self.kid = kid
        self.typ = typ
    }

}
