//
// PlanResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct PlanResponse: Codable {

    public var plan: Plan
    public var timeseries: TimeSeriesResponse

    public init(plan: Plan, timeseries: TimeSeriesResponse) {
        self.plan = plan
        self.timeseries = timeseries
    }

}
