//
// Plan.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct Plan: Codable {

    public var id: MongoObjectID
    public var name: String
    public var recurrings: [Recurring]
    public var allocations: [Allocation]
    public var events: [Event]

    public init(id: MongoObjectID, name: String, recurrings: [Recurring], allocations: [Allocation], events: [Event]) {
        self.id = id
        self.name = name
        self.recurrings = recurrings
        self.allocations = allocations
        self.events = events
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id = "_id"
        case name
        case recurrings
        case allocations
        case events
    }

}
