//
// PlanUpdatePayload.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct PlanUpdatePayload: Codable {

    public var name: String?
    public var recurrings: [Recurring]?
    public var allocations: [Allocation]?
    public var events: [Event]?

    public init(name: String? = nil, recurrings: [Recurring]? = nil, allocations: [Allocation]? = nil, events: [Event]? = nil) {
        self.name = name
        self.recurrings = recurrings
        self.allocations = allocations
        self.events = events
    }

}
