//
// Recurring.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct Recurring: Codable {

    public var id: MongoObjectID?
    public var name: String
    public var start: Int64
    public var end: Int64
    public var principal: Double
    public var amount: Double
    public var interest: Double
    public var frequency: TimeInterval

    public init(id: MongoObjectID? = nil, name: String, start: Int64, end: Int64, principal: Double, amount: Double, interest: Double, frequency: TimeInterval) {
        self.id = id
        self.name = name
        self.start = start
        self.end = end
        self.principal = principal
        self.amount = amount
        self.interest = interest
        self.frequency = frequency
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id = "_id"
        case name
        case start
        case end
        case principal
        case amount
        case interest
        case frequency
    }

}
