//
// SetAccountAsHiddenPayload.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct SetAccountAsHiddenPayload: Codable {

    public var itemId: String
    public var accountId: String
    public var hideOrNot: Bool

    public init(itemId: String, accountId: String, hideOrNot: Bool) {
        self.itemId = itemId
        self.accountId = accountId
        self.hideOrNot = hideOrNot
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case itemId = "item_id"
        case accountId = "account_id"
        case hideOrNot = "hide_or_not"
    }

}
