//
// SignupResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct SignupResponse: Codable { 


    public var email: String
    public var firstName: String
    public var lastName: String
    public var income: Double

    public init(email: String, firstName: String, lastName: String, income: Double) {
        self.email = email
        self.firstName = firstName
        self.lastName = lastName
        self.income = income
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case email
        case firstName = "first_name"
        case lastName = "last_name"
        case income
    }

}
