//
// SignupPayload.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct SignupPayload: Codable {

    public var email: String
    public var password: String
    public var firstName: String
    public var lastName: String
    public var income: Double
    public var location: Location
    public var birthday: Date

    public init(email: String, password: String, firstName: String, lastName: String, income: Double, location: Location, birthday: Date) {
        self.email = email
        self.password = password
        self.firstName = firstName
        self.lastName = lastName
        self.income = income
        self.location = location
        self.birthday = birthday
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case email
        case password
        case firstName = "first_name"
        case lastName = "last_name"
        case income
        case location
        case birthday
    }

}
