//
// Snapshot.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct Snapshot: Codable {

    public var netWorth: Money
    public var runningSavings: Money
    public var runningSpending: Money
    public var runningIncome: Money
    public var snapshotTime: Int64

    public init(netWorth: Money, runningSavings: Money, runningSpending: Money, runningIncome: Money, snapshotTime: Int64) {
        self.netWorth = netWorth
        self.runningSavings = runningSavings
        self.runningSpending = runningSpending
        self.runningIncome = runningIncome
        self.snapshotTime = snapshotTime
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case netWorth = "net_worth"
        case runningSavings = "running_savings"
        case runningSpending = "running_spending"
        case runningIncome = "running_income"
        case snapshotTime = "snapshot_time"
    }

}
