//
// TimeInterval.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct TimeInterval: Codable { 


    public enum Typ: String, Codable {
        case monthly = "monthly"
        case annually = "annually"
        case daily = "daily"
        case weekly = "weekly"
    }
    public var typ: Typ
    public var content: Int

    public init(typ: Typ, content: Int) {
        self.typ = typ
        self.content = content
    }

}
