//
// TimeSeriesResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Today&#39;s date, daily values of user&#39;s net worth */
public struct TimeSeriesResponse: Codable {

    public var start: Int
    public var series: [TimeSeriesEntry]

    public init(start: Int, series: [TimeSeriesEntry]) {
        self.start = start
        self.series = series
    }

}
