//
// TimePeriod.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct TimePeriod: Codable {

    public var start: Int
    public var end: Int

    public init(start: Int, end: Int) {
        self.start = start
        self.end = end
    }

}
