//
// TimeSeriesEntry.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Daily values of user&#39;s net worth */
public struct TimeSeriesEntry: Codable {

    public var date: Int
    public var netWorth: Money

    public init(date: Int, netWorth: Money) {
        self.date = date
        self.netWorth = netWorth
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case date
        case netWorth = "net_worth"
    }

}
