//
// TimeSeries.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

/** Daily values starting on some day. */
public struct TimeSeries: Codable { 


    public var startDay: Int
    public var series: [Double]

    public init(startDay: Int, series: [Double]) {
        self.startDay = startDay
        self.series = series
    }

    public enum CodingKeys: String, CodingKey, CaseIterable { 
        case startDay = "start_day"
        case series
    }

}
