//
// Transform.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct Transform: Codable { 


    public var trigger: Int
    public var change: [String:AssetToPercentMapping]

    public init(trigger: Int, change: [String:AssetToPercentMapping]) {
        self.trigger = trigger
        self.change = change
    }

}
