//
// Transform.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct Transform: Codable { 


    public var trigger: TimeInterval
    public var change: AssetChange

    public init(trigger: TimeInterval, change: AssetChange) {
        self.trigger = trigger
        self.change = change
    }

}
