//
// UpdateUserRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct UpdateUserRequest: Codable {

    public var email: String?
    public var password: String?
    public var firstName: String?
    public var lastName: String?
    public var income: Double?
    public var netWorth: Double?
    public var location: Location?
    public var birthday: Date?

    public init(email: String? = nil, password: String? = nil, firstName: String? = nil, lastName: String? = nil, income: Double? = nil, netWorth: Double? = nil, location: Location? = nil, birthday: Date? = nil) {
        self.email = email
        self.password = password
        self.firstName = firstName
        self.lastName = lastName
        self.income = income
        self.netWorth = netWorth
        self.location = location
        self.birthday = birthday
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case email
        case password
        case firstName = "first_name"
        case lastName = "last_name"
        case income
        case netWorth = "net_worth"
        case location
        case birthday
    }

}
