//
// UpdateUserRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct UpdateUserRequest: Codable { 


    public var password: String?
    public var firstName: String?
    public var lastName: String?
    public var income: Double?

    public init(password: String?, firstName: String?, lastName: String?, income: Double?) {
        self.password = password
        self.firstName = firstName
        self.lastName = lastName
        self.income = income
    }

    public enum CodingKeys: String, CodingKey { 
        case password
        case firstName = "first_name"
        case lastName = "last_name"
        case income
    }

}
