//
// UserLocation.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation


public struct UserLocation: Codable { 


    public var lat: Double
    public var lon: Double

    public init(lat: Double, lon: Double) {
        self.lat = lat
        self.lon = lon
    }

}
