//
// TimeseriesAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation



open class TimeseriesAPI {
    /**
     Get a user's projection timeseries
     
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func getTimeseries(completion: @escaping ((_ data: TimeSeries?,_ error: Error?) -> Void)) {
        getTimeseriesWithRequestBuilder().execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }

    /**
     Get a user's projection timeseries
     - GET /timeseries
     - API Key:
       - type: apiKey finch-sid 
       - name: sidCookie
     - returns: RequestBuilder<TimeSeries> 
     */
    open class func getTimeseriesWithRequestBuilder() -> RequestBuilder<TimeSeries> {
        let path = "/timeseries"
        let URLString = OpenAPIClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        
        let url = URLComponents(string: URLString)

        let requestBuilder: RequestBuilder<TimeSeries>.Type = OpenAPIClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

}
