on: [repository_dispatch, workflow_dispatch]

name: "Update FinchSwiftClient"

jobs:
  update-finch-swift-client:
    runs-on: macos-latest
    steps:
      # homebrew checks out the repo
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master

      - name: Install openapi generator
        id: install-openapi-generator
        run: brew install openapi-generator

      # - name: Purge codegened files
      #   id: purge-files
      #   run: rm ./OpenAPIClient/Classes/OpenAPIs

      - name: Get Api Spec
        id: get-api-spec
        run: "curl -H 'Authorization: token ${{ secrets.PFP_ACCESS_TOKEN }}' -H 'Accept: application/vnd.github.v4.raw' -o api.yaml -L https://api.github.com/repos/ucfinancegroup/pfp/postman/api.yaml"

      - name: Run codegen
        id: run-codegen
        run: openapi-generator generate -i ./api.yaml -g swift5 -o ./

      - name: Remove api.yaml
        id: remove-api-yaml
        run: rm api.yaml

      - name: add-and-commit
        uses: EndBug/add-and-commit@v7
        with:
          branch: main
          message: "Update FinchSwiftClient"
